In [3]:
# importing all the libraries
import pandas as pd
import numpy as np
import  difflib
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Preprocessing

In [4]:
# loading the data from the file
movies=pd.read_csv("Dataset\movies_data.csv")
movies

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [5]:
# printing first 5 rows from the dataframe
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [6]:
# number of Rows and Columns in data frame
movies.shape

(10000, 9)

In [7]:
# description about the data
movies.describe()

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [8]:
# information about the data
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB

In [9]:
# checking the null values
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [10]:
# cleaning the null values
movies=movies.fillna("")

In [11]:
# again checking the null values
movies.isnull().sum()

id                   0
title                0
genre                0
original_language    0
overview             0
popularity           0
release_date         0
vote_average         0
vote_count           0
dtype: int64

In [12]:
# name of each cloumns in dataframe
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [13]:
# Selecting the relevent features for recommendation

movies=movies[["title","overview","genre"]]
movies

,title,overview,genre
0,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"
2,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
3,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
...,...,...,...
9995,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy"
9996,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure"
9997,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War"
9998,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama"
9999,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime"

In [14]:
# Combining the two features with title of tags

movies["tags"] = movies["overview"] + movies["genre"] +  movies["title"]
movies

,title,overview,genre,tags
0,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo..."
9996,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...
9997,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War","During World War II, a brave, patriotic Americ..."
9998,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...
9999,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...

In [15]:
# Removing these two features after forming the tags title

new_data = movies.drop(columns=["overview","genre","title"])
new_data

                                                   tags
0     Framed in the 1940s for the double murder of h...
1     Raj is a rich, carefree, happy-go-lucky second...
2     Spanning the years 1945 to 1955, a chronicle o...
3     The true story of how businessman Oskar Schind...
4     In the continuing saga of the Corleone crime f...
...                                                 ...
9995  The story follows the adventures of Aang, a yo...
9996  The sharks take bite out of the East Coast whe...
9997  During World War II, a brave, patriotic Americ...
9998  A man named Farmer sets out to rescue his kidn...
9999  Seeking justice for his partner’s murder by an...

[10000 rows x 1 columns]

In [16]:
#converting the text into feature vectors
cv = CountVectorizer(max_features=10000, stop_words="english")
cv

CountVectorizer(max_features=10000, stop_words='english')

In [17]:
# converting in array form
vector=cv.fit_transform(new_data["tags"].values.astype("U")).toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
# number of Rows and Columns
vector.shape

(10000, 10000)

In [19]:
# getting the similarity using using cosine similarity

similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.05555556, 0.08006408, ..., 0.0729325 , 0.06804138,
        0.0347524 ],
       [0.05555556, 1.        , 0.08006408, ..., 0.        , 0.        ,
        0.        ],
       [0.08006408, 0.08006408, 1.        , ..., 0.02335709, 0.03268602,
        0.        ],
       ...,
       [0.0729325 , 0.        , 0.02335709, ..., 1.        , 0.02977457,
        0.03041495],
       [0.06804138, 0.        , 0.03268602, ..., 0.02977457, 1.        ,
        0.04256283],
       [0.0347524 , 0.        , 0.        , ..., 0.03041495, 0.04256283,
        1.        ]])

In [20]:
# number of Rows and Columns
similarity.shape

(10000, 10000)

In [21]:
# getting the movie name from the user
movie_name =input("Enter your favourite movie name: ")

In [22]:
# make a list with all the movies name given in the dataset
list_of_all_titles=movies["title"].tolist()
list_of_all_titles

['The Shawshank Redemption',
 'Dilwale Dulhania Le Jayenge',
 'The Godfather',
 "Schindler's List",
 'The Godfather: Part II',
 'Impossible Things',
 'Spirited Away',
 'Your Eyes Tell',
 'Dou kyu sei – Classmates',
 'Your Name.',
 '12 Angry Men',
 "Gabriel's Inferno",
 'Parasite',
 'The Green Mile',
 "Gabriel's Inferno: Part II",
 'The Dark Knight',
 'The Good, the Bad and the Ugly',
 'Pulp Fiction',
 'The Lord of the Rings: The Return of the King',
 "Gabriel's Inferno: Part III",
 'Forrest Gump',
 'Cinema Paradiso',
 'Seven Samurai',
 'GoodFellas',
 'Violet Evergarden: The Movie',
 'Life Is Beautiful',
 'Once Upon a Time in America',
 'Harakiri',
 'Psycho',
 'Josee, the Tiger and the Fish',
 "A Dog's Will",
 'Grave of the Fireflies',
 "One Flew Over the Cuckoo's Nest",
 'Fight Club',
 'Evangelion: 3.0+1.0 Thrice Upon a Time',
 'Spider-Man: Into the Spider-Verse',
 'City of God',
 'Hope',
 'A Silent Voice: The Movie',
 'Hotarubi no Mori e',
 "Howl's Moving Castle",
 'Neon Genesis Evangelion: The End of Evangelion',
 'The Empire Strikes Back',
 'Sunset Boulevard',
 'Wolfwalkers',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Ikiru',
 'Primal: Tales of Savagery',
 'The Pianist',
 'Interstellar',
 'Whiplash',
 'The Lord of the Rings: The Two Towers',
 'American History X',
 'Rear Window',
 'Inception',
 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
 'Given',
 'City Lights',
 'High and Low',
 'The Great Dictator',
 'Se7en',
 'Top Gun: Maverick',
 'Princess Mononoke',
 'Dedicated to my ex',
 'The Silence of the Lambs',
 'Come and See',
 'Clouds',
 'Dead Poets Society',
 'Modern Times',
 'Five Feet Apart',
 'Léon: The Professional',
 'Once Upon a Time in the West',
 'Hamilton',
 'Paths of Glory',
 'Justice League Dark: Apokolips War',
 'Back to the Future',
 'My Hero Academia: Heroes Rising',
 'Life in a Year',
 'Better Days',
 'Woman in the Dunes',
 'We All Loved Each Other So Much',
 'Tokyo Story',
 'Perfect Blue',
 'The Legend of 1900',
 'Apocalypse Now',
 'Rascal Does Not Dream of a Dreaming Girl',
 'Avengers: Endgame',
 'Le Trou',
 'Miracle in Cell No. 7',
 'Mommy',
 'Oldboy',
 'Steven Universe: The Movie',
 'The Art of Racing in the Rain',
 "Zack Snyder's Justice League",
 'Klaus',
 'The Handmaiden',
 'Avengers: Infinity War',
 'The Intouchables',
 "KonoSuba: God's Blessing on this Wonderful World! Legend of Crimson",
 'Everything Everywhere All at Once',
 'The Lion King',
 "It's a Wonderful Life",
 'Persona',
 'Black Beauty',
 'Bicycle Thieves',
 'Wolf Children',
 'Maquia: When the Promised Flower Blooms',
 'Il Sorpasso',
 'Green Book',
 'Violet Evergarden: Eternity and the Auto Memory Doll',
 'I Want to Eat Your Pancreas',
 'Sansho the Bailiff',
 'Witness for the Prosecution',
 'Miraculous World: New York, United HeroeZ',
 "Mortal Kombat Legends: Scorpion's Revenge",
 'New Gods: Nezha Reborn',
 'Stalker',
 '8½',
 'The Kid',
 'The Apartment',
 'Bo Burnham: Inside',
 'Coco',
 'The Shining',
 'Doctor Who: The Day of the Doctor',
 'A Clockwork Orange',
 'The Seventh Seal',
 'Investigation of a Citizen Above Suspicion',
 'Vertigo',
 'The Hate U Give',
 'Children of Paradise',
 'Portrait of a Lady on Fire',
 'Inglourious Basterds',
 'Along with the Gods: The Last 49 Days',
 'Call Me by Your Name',
 'Star Wars',
 'The Usual Suspects',
 'Gladiator',
 'Piper',
 'The Prestige',
 'Saving Private Ryan',
 'Memento',
 'Shutter Island',
 'The Matrix',
 'My Mom is a Character 3',
 'Capernaum',
 'The Help',
 'Hacksaw Ridge',
 'Soul',
 'Taxi Driver',
 'Wonder',
 "Singin' in the Rain",
 'Metropolis',
 'Yojimbo',
 'Joker',
 'All About Eve',
 'Scenes from a Marriage',
 'Casablanca',
 'La Dolce Vita',
 'Bo Burnham: Make Happy',
 'Andrei Rublev',
 'The Father',
 'Scarface',
 'My Friends',
 'The Departed',
 'Rashomon',
 'Lock, Stock and Two Smoking Barrels',
 'Ayla: The Daughter of War',
 'Togo',
 'Double Indemnity',
 'Central Station',
 'Sherlock Jr.',
 "Me Against You: Mr. S's Vendetta",
 'Out of the Clear Blue Sky',
 'Nobody',
 'Reservoir Dogs',
 'Django Unchained',
 'Far From the Tree',
 'The Great War',
 'Cruella',
 'Full Metal Jacket',
 'Good Will Hunting',
 'Some Like It Hot',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Wild Strawberries',
 'Alien',
 'Paper Lives',
 'The Invisible Guest',
 'Paris, Texas',
 'How to Train Your Dragon: Homecoming',
 'Dersu Uzala',
 'Pather Panchali',
 'The Tale of The Princess Kaguya',
 'Anne of Green Gables',
 'Harry Potter and the Deathly Hallows: Part 2',
 "Michael Jackson's Thriller",
 'Big Deal on Madonna Street',
 'The Truman Show',
 'Red Beard',
 'M',
 'Believe Me: The Abduction of Lisa McVey',
 'In the Mood for Love',
 'Incendies',
 'A Special Day',
 'I corti',
 'There Will Be Blood',
 'Hannah Gadsby: Nanette',
 'Eternal Sunshine of the Spotless Mind',
 'Straight Outta Nowhere: Scooby-Doo! Meets Courage the Cowardly Dog',
 'The Hunt',
 'Three Billboards Outside Ebbing, Missouri',
 'Lion',
 'In the Arms of an Assassin',
 'Ugetsu',
 'Kitbull',
 'The Best of Youth',
 'Toto, Peppino, and the Hussy',
 'The Passion of Joan of Arc',
 'The 400 Blows',
 'Scooby-Doo! and Kiss: Rock and Roll Mystery',
 'La Haine',
 'Love, Simon',
 'Das Boot',
 'Pride & Prejudice',
 'The Elephant Man',
 'Mirror',
 'A Taxi Driver',
 'Silenced',
 'Ran',
 '2001: A Space Odyssey',
 'Jojo Rabbit',
 'Bound by Honor',
 'Terminator 2: Judgment Day',
 'Doctor Who: The Time of the Doctor',
 'Rocco and His Brothers',
 'My Neighbor Totoro',
 'The Red Shoes',
 'Late Spring',
 'Nights of Cabiria',
 'Memories of Murder',
 "Ron's Gone Wrong",
 'Love Exposure',
 "A Dog's Journey",
 'Loving Vincent',
 'WALL·E',
 'Hidden Figures',
 'Prisoners',
 'Elite Squad',
 "Cool Kids Don't Cry",
 'My Name Is Khan',
 'Judgment at Nuremberg',
 'On My Skin',
 'Weathering with You',
 'Finch',
 'Room',
 'The Grand Budapest Hotel',
 'Poverty and Nobility',
 'Sing 2',
 'Gifted',
 'Spider-Man: No Way Home',
 'In a Heartbeat',
 'Along with the Gods: The Two Worlds',
 'The Lives of Others',
 'All My Life',
 'The Sting',
 'To Kill a Mockingbird',
 'The Wages of Fear',
 'Wish Dragon',
 'Innocent Voices',
 'The Circus',
 'Chungking Express',
 'The General',
 'The Second Mother',
 'Prayers for Bobby',
 'For a Few Dollars More',
 'Song of the Sea',
 'In This Corner of the World',
 'The Young and the Damned',
 'The Treasure of the Sierra Madre',
 'Dial M for Murder',
 'Palmer',
 'Bingo: The King of the Mornings',
 'The Hidden Fortress',
 'CODA',
 'Veinteañera, Divorciada y Fantástica',
 'Ivan Vasilyevich Changes His Profession',
 'The Gold Rush',
 'Requiem for a Dream',
 'Rome, Open City',
 'American Beauty',
 'The Cranes Are Flying',
 'The Wolf of Wall Street',
 'Citizen Kane',
 'El mesero',
 'Miracle in Cell No. 7',
 'The Deer Hunter',
 'A Man Escaped',
 'Nobody Knows',
 'Amadeus',
 'The Boy and the Beast',
 'No Manches Frida 2',
 'Where Hands Touch',
 'Autumn Sonata',
 'Harry Potter and the Prisoner of Azkaban',
 'The Thing',
 'Bohemian Rhapsody',
 'On the Waterfront',
 'The Imitation Game',
 'Like Stars on Earth',
 'Casino',
 'Belle',
 'The Mitchells vs. the Machines',
 "Hachi: A Dog's Tale",
 'Pink Floyd: The Wall',
 'The Way He Looks',
 'The Secret in Their Eyes',
 'Tae Guk Gi: The Brotherhood of War',
 'Forgotten',
 'Gone with the Wind',
 'A Whisker Away',
 'Paperman',
 'Gran Torino',
 'Barry Lyndon',
 'La Notte',
 'Ford v Ferrari',
 'Sanjuro',
 'When Marnie Was There',
 'North by Northwest',
 'Dangal',
 'My Way',
 'Scooby-Doo! and the Curse of the 13th Ghost',
 'Rope',
 'Raging Bull',
 'The Third Man',
 "Operation Y and Other Shurik's Adventures",
 'The Exterminating Angel',
 'The Shop Around the Corner',
 'Castaway on the Moon',
 'Limelight',
 'Raya and the Last Dragon',
 'Inner Workings',
 'Cries and Whispers',
 "Remi, Nobody's Boy",
 'Batman: The Dark Knight Returns, Part 2',
 'Words on Bathroom Walls',
 'Army of Shadows',
 'An Egg Rescue',
 'Bad Genius',
 '3 Idiots',
 'Trainspotting',
 '1917',
 'Lawrence of Arabia',
 "It's Such a Beautiful Day",
 'Castle in the Sky',
 'Scooby-Doo! Camp Scare',
 'Divorce Italian Style',
 'La Strada',
 'Kill Bill: Vol. 1',
 'Three Men and a Leg',
 'A Trip to the Moon',
 'Three Colors: Red',
 'Girl in the Basement',
 'What Ever Happened to Baby Jane?',
 'Raise the Red Lantern',
 'Toy Story',
 'The Battle of Algiers',
 'Throne of Blood',
 'Million Dollar Baby',
 "My Father's Violin",
 'Kill Bill: The Whole Bloody Affair',
 'My Hero Academia: Two Heroes',
 'The Cameraman',
 'Before Sunrise',
 'Children of Heaven',
 "Where Is My Friend's House?",
 'The Tomorrow War',
 'The Cabinet of Dr. Caligari',
 'Akira',
 'Amarcord',
 'Catch Me If You Can',
 '12 Years a Slave',
 'La Maison en Petits Cubes',
 'The Postman',
 'The Great Escape',
 'Close to the Horizon',
 'Us Again',
 'Flipped',
 'Invisible Life',
 'Dallas Buyers Club',
 'The Black Phone',
 'The Boy Who Harnessed the Wind',
 'The Sixth Sense',
 'Just Mercy',
 'Tel chi el telùn',
 'Up',
 'Teen Titans Go! vs. Teen Titans',
 'Charm City Kings',
 'The Greatest Showman',
 'Ghost in the Shell',
 'Mr. Smith Goes to Washington',
 'Rebecca',
 'Vincent',
 'Unforgiven',
 'The Breadwinner',
 'La Grande Vadrouille',
 'Young Frankenstein',
 'Luca',
 'Captain Fantastic',
 'Freedom Writers',
 'Inside Out',
 'Ordet',
 'Ace in the Hole',
 'Two Women',
 'Persepolis',
 'Braveheart',
 'Blade Runner',
 'Cousins',
 'Mulan',
 'No Country for Old Men',
 'La Jetée',
 'My Little Pony: A New Generation',
 'Chinatown',
 'Jurassic Park',
 'A Separation',
 'Nausicaä of the Valley of the Wind',
 'Raiders of the Lost Ark',
 'To Live',
 'Faust',
 'Whisper of the Heart',
 'Ne Zha',
 'Little Women',
 'The Iron Giant',
 'In the Name of the Father',
 "Harry Potter and the Philosopher's Stone",
 'Justice League: The Flashpoint Paradox',
 'Mamma Roma',
 'Z',
 'Aliens',
 'Sunrise: A Song of Two Humans',
 'Louis C.K.: Hilarious',
 '1900',
 'The Night of the Hunter',
 'About Time',
 'To Be or Not to Be',
 'Guardians of the Galaxy',
 'Winter Light',
 'Return of the Jedi',
 'Amélie',
 'Minha Vida em Marte',
 'Sing Street',
 'The Pursuit of Happyness',
 'Letter from an Unknown Woman',
 'Roman Holiday',
 "You've Got This",
 'The Working Class Goes to Heaven',
 "Ivan's Childhood",
 'The Specials',
 'Yi Yi',
 'It Happened One Night',
 'Dancer in the Dark',
 'La luna',
 'Heat',
 'V for Vendetta',
 'Rio Bravo',
 'Sherlock: The Abominable Bride',
 'Scooby-Doo! and the Samurai Sword',
 'Tokyo Godfathers',
 'Whiplash',
 'Bajrangi Bhaijaan',
 'Me Before You',
 'A Street Cat Named Bob',
 'Nostalgia',
 'The Cure',
 'Farewell My Concubine',
 'Miraculous World: Shanghai – The Legend of Ladydragon',
 'Gone Girl',
 'The Seven Deadly Sins: Cursed by Light',
 'A Fistful of Dollars',
 'Monsieur Verdoux',
 'Day for Night',
 'Paper Moon',
 'Diabolique',
 'Always',
 'See You Up There',
 'La La Land',
 'Tampopo',
 'World of Tomorrow',
 'The Diamond Arm',
 'Perfect Strangers',
 'Departures',
 'Fargo',
 'The Notebook',
 'Solaris',
 'Kill Bill: Vol. 2',
 'The Theory of Everything',
 'Umberto D.',
 'Shoplifters',
 'Titanic',
 'Safety Last!',
 'Joint Security Area',
 'Le Samouraï',
 'Evangelion: 2.0 You Can (Not) Advance',
 'Rififi',
 'Dune',
 'Network',
 'The Miracle Worker',
 'Stand by Me',
 'A Bag of Marbles',
 'Anatomy of a Murder',
 'Werckmeister Harmonies',
 'Isle of Dogs',
 'Her',
 'Millennium Actress',
 'Rurouni Kenshin: The Final',
 'Feast',
 'Hustle',
 'Cindy La Regia',
 'No Game No Life: Zero',
 'Hiroshima Mon Amour',
 'Knives Out',
 'Drishyam',
 'Papillon',
 'We Bare Bears: The Movie',
 'King Richard',
 'Through a Glass Darkly',
 'Mulholland Dr.',
 'Kagemusha',
 'We Are the Nobles',
 'Dances with Wolves',
 'The Normal Heart',
 'Mary and Max',
 'The Boy in the Striped Pyjamas',
 'A Beautiful Mind',
 'Polisse',
 'The Ox-Bow Incident',
 'Elite Squad: The Enemy Within',
 'Mr. Nobody',
 'Ben-Hur',
 'The Grapes of Wrath',
 'Anonymously Yours',
 'Wild Tales',
 'Vivre Sa Vie',
 'Grand Illusion',
 'Wings of Desire',
 'The Big Lebowski',
 'The Marquis of Grillo',
 'Partly Cloudy',
 'Interstella 5555: The 5tory of the 5ecret 5tar 5ystem',
 'Warrior',
 "Don't Be Bad",
 'The Best Offer',
 'The Phantom Carriage',
 "Kiki's Delivery Service",
 "Carlito's Way",
 'Kabhi Khushi Kabhie Gham',
 'An Autumn Afternoon',
 'The Nightmare Before Christmas',
 'Jujutsu Kaisen 0',
 'Dragon Ball Super: Broly',
 'Love, Rosie',
 'Mulholland Drive',
 'The Best Years of Our Lives',
 'Regular Show: The Movie',
 'The Last: Naruto the Movie',
 'Forbidden Games',
 'Spring, Summer, Fall, Winter... and Spring',
 'The Heist of the Century',
 'Crooks in Clover',
 'A Moment to Remember',
 'Mortal Kombat Legends: Battle of the Realms',
 "L'Eclisse",
 'Downfall',
 'Freaks',
 'The Virgin Spring',
 'Land of Mine',
 'A Short Film About Love',
 'Indiana Jones and the Last Crusade',
 'The Last Laugh',
 'Finding Nemo',
 'Dog Day Afternoon',
 "Rosemary's Baby",
 'Monsters, Inc.',
 'Infernal Affairs',
 'Into the Wild',
 'The Bridge on the River Kwai',
 'Harry Potter and the Goblet of Fire',
 "Who's Afraid of Virginia Woolf?",
 'Bacurau',
 'Fail Safe',
 'The Valet',
 'Before Sunset',
 'Spotlight',
 'White Collar Blues',
 'Inherit the Wind',
 '3-Iron',
 'Gone Mom: The Disappearance of Jennifer Dulos',
 'Brokeback Mountain',
 'Logan',
 'Descendants 3',
 'A Woman Under the Influence',
 'Monty Python and the Holy Grail',
 'My Life as a Zucchini',
 'Never Look Away',
 'Midnight Sun',
 'Rich in Love',
 "God's Own Country",
 'No Manches Frida',
 'Gifted Hands: The Ben Carson Story',
 'Manhattan',
 'Fabricated City',
 'Fanny and Alexander',
 'Deep Red',
 'Notorious',
 'War Room',
 'Presto',
 'Snatch',
 'Constantine: City of Demons - The Movie',
 "They Shoot Horses, Don't They?",
 'Toy Story 3',
 'How to Train Your Dragon',
 'Touch of Evil',
 'Trollhunters: Rise of the Titans',
 'Lisbela and the Prisoner',
 'Shelter',
 'The King of Comedy',
 'Donnie Darko',
 'The Kissing Booth 2',
 'Maudie',
 'The Wind Rises',
 'Do the Right Thing',
 'All Quiet on the Western Front',
 'The Chaser',
 'Dogville',
 'Coraline',
 'Mustang',
 'Ernest & Celestine',
 'The Man Who Shot Liberty Valance',
 'White Snake',
 'Straight Outta Compton',
 'Back to the Outback',
 'Bad Seeds',
 'Paprika',
 'Brief Encounter',
 'If Anything Happens I Love You',
 'Marriage Italian Style',
 'The King and the Mockingbird',
 "I Don't Want to Go Back Alone",
 'I Saw the Devil',
 'Teen Titans: Trouble in Tokyo',
 'Kizumonogatari Part 1: Tekketsu',
 'Short Term 12',
 'PlayTime',
 'Annie Hall',
 'The Bad Guys',
 'tick, tick... BOOM!',
 "Angel's Egg",
 'Batman: Under the Red Hood',
 'The Color Purple',
 'One Hundred Steps',
 'Pride',
 'A Matter of Life and Death',
 'Nothing Left to Do but Cry',
 'L.A. Confidential',
 'Ratatouille',
 'The Twilight Samurai',
 'Harry Potter and the Deathly Hallows: Part 1',
 'K-12',
 "The Children's Hour",
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The Perks of Being a Wallflower',
 'Elvis',
 'Doctor Who: Last Christmas',
 'Selena',
 'A Bronx Tale',
 'Onward',
 'Ninja Scroll',
 'Rurouni Kenshin: The Beginning',
 'How to Train Your Dragon: The Hidden World',
 'Nine Queens',
 'The Girl Who Leapt Through Time',
 'Porco Rosso',
 'Rocky',
 'The Untouchables',
 'The Witch: Part 1. The Subversion',
 'Marriage Story',
 'The Maltese Falcon',
 'Big Fish',
 'Holding the Man',
 'Rurouni Kenshin Part III: The Legend Ends',
 'The Dark Knight Rises',
 'Temple Grandin',
 'Life of Brian',
 'Train to Busan',
 'Three Steps Above Heaven',
 'Fantastic Mr. Fox',
 'The Breakfast Club',
 'War of Likes',
 'Batman: The Dark Knight Returns, Part 1',
 'Amour',
 'Cool Hand Luke',
 'Meshes of the Afternoon',
 'Red Shoes and the Seven Dwarfs',
 'BPM (Beats per Minute)',
 'Godzilla vs. Kong',
 'Divines',
 'Day & Night',
 'Awakenings',
 'The Dinner Game',
 'Stalag 17',
 'The Trial of the Chicago 7',
 'The Batman',
 'Mother',
 'Fiddler on the Roof',
 'Rain Man',
 'Z-O-M-B-I-E-S 2',
 'Onibaba',
 'Sound of Metal',
 'Duck, You Sucker',
 'Corpus Christi',
 'El Infierno',
 "I'm No Longer Here",
 'The Hustler',
 'Die Hard',
 'I, Daniel Blake',
 'My Mom is a Character',
 "Geri's Game",
 'Accattone',
 'The Celebration',
 'The Turin Horse',
 'The Searchers',
 'The Blues Brothers',
 'Big Hero 6',
 'A Walk to Remember',
 'Misery',
 'Platoon',
 'Mystic River',
 'Two Is a Family',
 'Zootopia',
 "Pan's Labyrinth",
 'Ali: Fear Eats the Soul',
 'Ip Man',
 'Sword Art Online: The Movie – Ordinal Scale',
 'Back to the Future Part II',
 'Ricky Gervais: Humanity',
 'The Shadow in My Eye',
 'Tod@s Caen',
 'Kwaidan',
 'The Ten Commandments',
 'Still Walking',
 'Time of the Gypsies',
 'Barbie in The 12 Dancing Princesses',
 'Beauty and the Beast',
 'Scent of a Woman',
 'The Straight Story',
 'The Hateful Eight',
 "The King's Speech",
 'The Spirit of the Beehive',
 'Philadelphia',
 'My Friends Act II',
 'Cléo from 5 to 7',
 'Slumdog Millionaire',
 'The Broken Circle Breakdown',
 'Dave Chappelle: The Age of Spin',
 'The Red Balloon',
 'Strangers on a Train',
 'Fantastic Planet',
 'Harry Potter and the Chamber of Secrets',
 'Sleuth',
 'The Traitor',
 'Underground',
 'System Crasher',
 'Ponyo',
 'Mildred Pierce',
 'The Tenant',
 'Nosferatu',
 'Fallen Angels',
 'The Killer',
 'Hotel Rwanda',
 'Sweet Smell of Success',
 'Magnolia',
 'The Big Heat',
 'The Leopard',
 'Cat on a Hot Tin Roof',
 'Wrath of Man',
 'Charade',
 'Stagecoach',
 'Heroic Losers',
 'For Love and Gold',
 'Harvey',
 'Another Round',
 'The Big Bad Fox and Other Tales',
 'The Exorcist',
 'The Chorus',
 "My Night at Maud's",
 'The Sound of Music',
 'In the Heat of the Night',
 'Edward Scissorhands',
 'A Werewolf Boy',
 '12 Angry Men',
 'Hunt for the Wilderpeople',
 'Fireworks',
 'Tangerines',
 'The Avengers',
 'Out of the Past',
 'The Wrong Trousers',
 "Azur & Asmar: The Princes' Quest",
 'Harry Potter and the Half-Blood Prince',
 'A Streetcar Named Desire',
 'One Cut of the Dead',
 'Rush',
 'Scarlet Street',
 'Kuch Kuch Hota Hai',
 "All the President's Men",
 'Embrace of the Serpent',
 'Cowboy Bebop: The Movie',
 'The Conformist',
 "Breakfast at Tiffany's",
 'The Man from Nowhere',
 'Shrek',
 'Three Colors: Blue',
 'Laurence Anyways',
 'The Incredibles',
 'Andhadhun',
 'Viridiana',
 'PK',
 'Don Camillo',
 'Batman Begins',
 'Moonrise Kingdom',
 'Spirit: Stallion of the Cimarron',
 'Feel the Beat',
 'Harry Potter and the Order of the Phoenix',
 'Brazil',
 "To All the Boys I've Loved Before",
 'All the Bright Places',
 'A Charlie Brown Christmas',
 'Angels with Dirty Faces',
 'High Noon',
 'Germany, Year Zero',
 'Sonic the Hedgehog 2',
 'Nightcrawler',
 'Free Fall',
 'The Warriors',
 'Laura',
 'Mississippi Burning',
 'Black Cat, White Cat',
 'The Sacrifice',
 'I Vitelloni',
 'The Sicilian Clan',
 'The Big Sleep',
 'The Killing',
 'To All the Boys: Always and Forever',
 'The Gangster, the Cop, the Devil',
 'The Gentlemen',
 'The Young Girls of Rochefort',
 'Fried Green Tomatoes',
 'Spies in Disguise',
 'Il Divo',
 'The Rules of the Game',
 'Stand and Deliver',
 'Black Narcissus',
 'Victoria',
 'Dreams',
 'Hair Love',
 'Captain America: The Winter Soldier',
 'Evangelion: 1.0 You Are (Not) Alone',
 'Memoirs of a Geisha',
 'The Bridges of Madison County',
 'Roma',
 'Encanto',
 "What's Eating Gilbert Grape",
 'White Heat',
 '2 Hearts',
 'Boys',
 'Eddie Murphy: Delirious',
 'Shang-Chi and the Legend of the Ten Rings',
 'All About My Mother',
 'Kubo and the Two Strings',
 'Steamboat Bill, Jr.',
 'Who Am I',
 'A Movie of Eggs',
 'The Martian',
 'Winter Sleep',
 'Instructions Not Included',
 'Jean de Florette',
 'How to Train Your Dragon 2',
 'Synecdoche, New York',
 'The Ghost and Mrs. Muir',
 'The Graduate',
 'The Philadelphia Story',
 'Harold and Maude',
 'Jules and Jim',
 'The Last Picture Show',
 'Ask Me If I Am Happy',
 'Kind Hearts and Coronets',
 'The Princess Bride',
 'Elevator to the Gallows',
 'Little Miss Sunshine',
 'Au Hasard Balthazar',
 'The Blind Side',
 'The Lost Weekend',
 'The Witcher: Nightmare of the Wolf',

In [23]:
# finding the close match for the movie name given by the user
related_movie=difflib.get_close_matches(movie_name,list_of_all_titles)
related_movie

['Iron Man', 'Iron Man 3', 'Iron Man 2']

In [24]:
# matched with the movies name given in the user
matched = related_movie[0]
matched

'Iron Man'

In [25]:
# finding the index of the movie name
index_of_movie = movies[movies.title==matched].index[0]
index_of_movie

969

In [26]:
# getting the list of similar movies
similarity_score = list(enumerate(similarity[index_of_movie]))
similarity_score

[(0, 0.0),
 (1, 0.0),
 (2, 0.0),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0625),
 (6, 0.0),
 (7, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (11, 0.048112522432468816),
 (12, 0.0),
 (13, 0.042874646285627205),
 (14, 0.0),
 (15, 0.036084391824351615),
 (16, 0.051031036307982884),
 (17, 0.10425720702853739),
 (18, 0.0),
 (19, 0.0),
 (20, 0.057353933467640436),
 (21, 0.0),
 (22, 0.044194173824159216),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.037688918072220454),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.05),
 (34, 0.11572751247156893),
 (35, 0.18569533817705186),
 (36, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.07624928516630233),
 (42, 0.11572751247156893),
 (43, 0.0),
 (44, 0.042874646285627205),
 (45, 0.03904344047215152),
 (46, 0.06933752452815364),
 (47, 0.0625),
 (48, 0.0),
 (49, 0.05892556509887897),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.1599005372667078),
 (55, 0.042874646285627205),
 (56, 0.0),
 (57, 0.0),
 (58, 0.06933752452815364),
 (59, 0.0),
 (60, 0.0),
 (61, 0.04902903378454601),
 (62, 0.0),
 (63, 0.0),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.0),
 (68, 0.0),
 (69, 0.0),
 (70, 0.04490132550669373),
 (71, 0.0),
 (72, 0.0),
 (73, 0.0),
 (74, 0.06804138174397717),
 (75, 0.08111071056538127),
 (76, 0.036860489038724284),
 (77, 0.0),
 (78, 0.06933752452815364),
 (79, 0.07216878364870323),
 (80, 0.0),
 (81, 0.0),
 (82, 0.0),
 (83, 0.0),
 (84, 0.0),
 (85, 0.0),
 (86, 0.08838834764831843),
 (87, 0.0),
 (88, 0.0),
 (89, 0.0),
 (90, 0.0),
 (91, 0.09284766908852593),
 (92, 0.0),
 (93, 0.09805806756909202),
 (94, 0.0),
 (95, 0.07537783614444091),
 (96, 0.07808688094430304),
 (97, 0.06933752452815364),
 (98, 0.0),
 (99, 0.12909944487358055),
 (100, 0.0),
 (101, 0.0),
 (102, 0.0),
 (103, 0.0),
 (104, 0.11180339887498948),
 (105, 0.0),
 (106, 0.0),
 (107, 0.0472455591261534),
 (108, 0.04564354645876384),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0),
 (112, 0.0),
 (113, 0.0),
 (114, 0.05976143046671968),
 (115, 0.05892556509887897),
 (116, 0.10206207261596577),
 (117, 0.0),
 (118, 0.0),
 (119, 0.0),
 (120, 0.053300179088902604),
 (121, 0.0),
 (122, 0.0),
 (123, 0.0944911182523068),
 (124, 0.07624928516630233),
 (125, 0.0),
 (126, 0.0),
 (127, 0.0),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (131, 0.03904344047215152),
 (132, 0.0625),
 (133, 0.0625),
 (134, 0.16666666666666666),
 (135, 0.038124642583151166),
 (136, 0.03434014098717226),
 (137, 0.0),
 (138, 0.057353933467640436),
 (139, 0.046423834544262965),
 (140, 0.04351941398892446),
 (141, 0.0),
 (142, 0.10206207261596577),
 (143, 0.0),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (148, 0.0545544725589981),
 (149, 0.0),
 (150, 0.0),
 (151, 0.046423834544262965),
 (152, 0.0),
 (153, 0.0),
 (154, 0.0),
 (155, 0.0),
 (156, 0.0),
 (157, 0.053300179088902604),
 (158, 0.048112522432468816),
 (159, 0.0),
 (160, 0.057353933467640436),
 (161, 0.09682458365518541),
 (162, 0.0),
 (163, 0.0),
 (164, 0.09128709291752768),
 (165, 0.0),
 (166, 0.0),
 (167, 0.053300179088902604),
 (168, 0.0),
 (169, 0.0),
 (170, 0.0625),
 (171, 0.05892556509887897),
 (172, 0.0),
 (173, 0.048112522432468816),
 (174, 0.0),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0),
 (182, 0.0),
 (183, 0.0),
 (184, 0.037688918072220454),
 (185, 0.0),
 (186, 0.0),
 (187, 0.06063390625908324),
 (188, 0.03227486121839514),
 (189, 0.11785113019775793),
 (190, 0.0),
 (191, 0.0),
 (192, 0.0),
 (193, 0.044194173824159216),
 (194, 0.0),
 (195, 0.0),
 (196, 0.0),
 (197, 0.0),
 (198, 0.040555355282690636),
 (199, 0.0),
 (200, 0.05590169943749474),
 (201, 0.0),
 (202, 0.04109974682633932),
 (203, 0.0),
 (204, 0.04003203845127178),
 (205, 0.0),
 (206, 0.11180339887498948),
 (207, 0.0),
 (208, 0.0),
 (209, 0.0),
 (210, 0.0),
 (211, 0.0),
 (212, 0.0),
 (213, 0.0),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (217, 0.0),
 (218, 0.025125945381480302),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0),
 (222, 0.0),
 (223, 0.12329924047901797),
 (224, 0.06063390625908324),
 (225, 0.12329924047901797),
 (226, 0.0),
 (227, 0.042874646285627205),
 (228, 0.1091089451179962),
 (229, 0.0),
 (230, 0.03254722774520597),
 (231, 0.08006407690254357),
 (232, 0.07715167498104596),
 (233, 0.0),
 (234, 0.0),
 (235, 0.0),
 (236, 0.0),
 (237, 0.0),
 (238, 0.038124642583151166),
 (239, 0.10425720702853739),
 (240, 0.042874646285627205),
 (241, 0.0),
 (242, 0.051031036307982884),
 (243, 0.03904344047215152),
 (244, 0.0),
 (245, 0.0),
 (246, 0.051031036307982884),
 (247, 0.03904344047215152),
 (248, 0.0),
 (249, 0.0),
 (250, 0.0),
 (251, 0.0),
 (252, 0.10660035817780521),
 (253, 0.12126781251816648),
 (254, 0.0),
 (255, 0.0),
 (256, 0.0),
 (257, 0.06933752452815364),
 (258, 0.17407765595569785),
 (259, 0.0),
 (260, 0.0),
 (261, 0.0),
 (262, 0.0),
 (263, 0.051031036307982884),
 (264, 0.042874646285627205),
 (265, 0.0),
 (266, 0.0),
 (267, 0.05892556509887897),
 (268, 0.0),
 (269, 0.0),
 (270, 0.08333333333333333),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.0),
 (275, 0.0),
 (276, 0.0),
 (277, 0.0),
 (278, 0.05),
 (279, 0.0),
 (280, 0.0),
 (281, 0.06804138174397717),
 (282, 0.0),
 (283, 0.0),
 (284, 0.053300179088902604),
 (285, 0.0),
 (286, 0.0),
 (287, 0.0),
 (288, 0.0),
 (289, 0.033709993123162106),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0668153104781061),
 (294, 0.0),
 (295, 0.05892556509887897),
 (296, 0.0),
 (297, 0.0),
 (298, 0.044194173824159216),
 (299, 0.0),
 (300, 0.0),
 (301, 0.0),
 (302, 0.0),
 (303, 0.04351941398892446),
 (304, 0.0),
 (305, 0.040555355282690636),
 (306, 0.0),
 (307, 0.0),
 (308, 0.0),
 (309, 0.07715167498104596),
 (310, 0.0),
 (311, 0.0),
 (312, 0.0),
 (313, 0.0),
 (314, 0.0),
 (315, 0.1091089451179962),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0),
 (320, 0.0),
 (321, 0.0),
 (322, 0.0),
 (323, 0.03904344047215152),
 (324, 0.09284766908852593),
 (325, 0.0),
 (326, 0.07537783614444091),
 (327, 0.0),
 (328, 0.08232319499226776),
 (329, 0.038124642583151166),
 (330, 0.0),
 (331, 0.0),
 (332, 0.07372097807744857),
 (333, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.11058146711617285),
 (339, 0.0625),
 (340, 0.0),
 (341, 0.0),
 (342, 0.18569533817705186),
 (343, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (347, 0.0),
 (348, 0.0),
 (349, 0.051031036307982884),
 (350, 0.0),
 (351, 0.0),
 (352, 0.057353933467640436),
 (353, 0.0),
 (354, 0.0),
 (355, 0.0),
 (356, 0.07216878364870323),
 (357, 0.03857583749052298),
 (358, 0.04902903378454601),
 (359, 0.0),
 (360, 0.0),
 (361, 0.0),
 (362, 0.0),
 (363, 0.0),
 (364, 0.0),
 (365, 0.0),
 (366, 0.0),
 (367, 0.0),
 (368, 0.06804138174397717),
 (369, 0.07537783614444091),
 (370, 0.0),
 (371, 0.0),
 (372, 0.0),
 (373, 0.0),
 (374, 0.15625),
 (375, 0.042257712736425826),
 (376, 0.11180339887498948),
 (377, 0.0),
 (378, 0.0),
 (379, 0.038124642583151166),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.0625),
 (385, 0.0),
 (386, 0.0),
 (387, 0.0545544725589981),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.04351941398892446),
 (392, 0.0),
 (393, 0.0),
 (394, 0.04109974682633932),
 (395, 0.0),
 (396, 0.0),
 (397, 0.09284766908852593),
 (398, 0.0),
 (399, 0.0),
 (400, 0.0),
 (401, 0.0),
 (402, 0.0),
 (403, 0.0),
 (404, 0.0),
 (405, 0.05212860351426869),
 (406, 0.0),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0),
 (410, 0.16666666666666666),
 (411, 0.0),
 (412, 0.0),
 (413, 0.04564354645876384),
 (414, 0.09805806756909202),
 (415, 0.03434014098717226),
 (416, 0.0),
 (417, 0.0),
 (418, 0.09805806756909202),
 (419, 0.0),
 (420, 0.0),
 (421, 0.07372097807744857),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (429, 0.0),
 (430, 0.09284766908852593),
 (431, 0.0),
 (432, 0.0),
 (433, 0.1599005372667078),
 (434, 0.0),
 (435, 0.0),
 (436, 0.08703882797784893),
 (437, 0.0),
 (438, 0.0545544725589981),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.0),
 (443, 0.16770509831248423),
 (444, 0.0),
 (445, 0.1091089451179962),
 (446, 0.0),
 (447, 0.0),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (454, 0.0),
 (455, 0.0),
 (456, 0.0),
 (457, 0.0),
 (458, 0.0),
 (459, 0.0),
 (460, 0.09128709291752768),
 (461, 0.09128709291752768),
 (462, 0.0),
 (463, 0.0),
 (464, 0.03904344047215152),
 (465, 0.0),
 (466, 0.0),
 (467, 0.12126781251816648),
 (468, 0.09302605094190634),
 (469, 0.0),
 (470, 0.0),
 (471, 0.0),
 (472, 0.0),
 (473, 0.05212860351426869),
 (474, 0.0625),
 (475, 0.0),
 (476, 0.040555355282690636),
 (477, 0.0),
 (478, 0.0),
 (479, 0.0668153104781061),
 (480, 0.0),
 (481, 0.02988071523335984),
 (482, 0.0),
 (483, 0.0),
 (484, 0.0),
 (485, 0.07216878364870323),
 (486, 0.04003203845127178),
 (487, 0.0),
 (488, 0.0),
 (489, 0.032826608214930636),
 (490, 0.08006407690254357),
 (491, 0.09284766908852593),
 (492, 0.051031036307982884),
 (493, 0.0),
 (494, 0.0),
 (495, 0.0),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.13258252147247765),
 (501, 0.1414213562373095),
 (502, 0.12329924047901797),
 (503, 0.0),
 (504, 0.0),
 (505, 0.0),
 (506, 0.0),
 (507, 0.0),
 (508, 0.0),
 (509, 0.0),
 (510, 0.14744195615489714),
 (511, 0.0472455591261534),
 (512, 0.0625),
 (513, 0.053300179088902604),
 (514, 0.0),
 (515, 0.0),
 (516, 0.04975185951049946),
 (517, 0.0),
 (518, 0.0),
 (519, 0.06454972243679027),
 (520, 0.12126781251816648),
 (521, 0.0),
 (522, 0.0),
 (523, 0.0),
 (524, 0.0),
 (525, 0.03857583749052298),
 (526, 0.0),
 (527, 0.0),
 (528, 0.04351941398892446),
 (529, 0.0314970394174356),
 (530, 0.0),
 (531, 0.0),
 (532, 0.0),
 (533, 0.03952847075210474),
 (534, 0.04490132550669373),
 (535, 0.1336306209562122),
 (536, 0.03254722774520597),
 (537, 0.0),
 (538, 0.0),
 (539, 0.0),
 (540, 0.0),
 (541, 0.03857583749052298),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0625),
 (545, 0.0),
 (546, 0.07216878364870323),
 (547, 0.0),
 (548, 0.0),
 (549, 0.0),
 (550, 0.0),
 (551, 0.0),
 (552, 0.0),
 (553, 0.0625),
 (554, 0.0),
 (555, 0.0),
 (556, 0.03857583749052298),
 (557, 0.09302605094190636),
 (558, 0.0),
 (559, 0.0),
 (560, 0.05),
 (561, 0.2165063509461097),
 (562, 0.036084391824351615),
 (563, 0.0),
 (564, 0.0),
 (565, 0.0),
 (566, 0.03500700210070024),
 (567, 0.0),
 (568, 0.1599005372667078),
 (569, 0.0),
 (570, 0.06804138174397717),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.0),
 (578, 0.0),
 (579, 0.0),
 (580, 0.0),
 (581, 0.03466876226407682),
 (582, 0.0),
 (583, 0.0),
 (584, 0.0),
 (585, 0.0),
 (586, 0.0),
 (587, 0.0),
 (588, 0.0),
 (589, 0.0),
 (590, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.08574929257125441),
 (594, 0.0),
 (595, 0.0),
 (596, 0.09622504486493763),
 (597, 0.0),
 (598, 0.0),
 (599, 0.02988071523335984),
 (600, 0.0),
 (601, 0.0),
 (602, 0.0),
 (603, 0.0),
 (604, 0.0),
 (605, 0.0),
 (606, 0.0),
 (607, 0.0),
 (608, 0.053300179088902604),
 (609, 0.0),
 (610, 0.0),
 (611, 0.0),
 (612, 0.057353933467640436),
 (613, 0.0),
 (614, 0.0625),
 (615, 0.029260286799032642),
 (616, 0.0),
 (617, 0.0),
 (618, 0.0),
 (619, 0.08006407690254357),
 (620, 0.06454972243679027),
 (621, 0.02988071523335984),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (626, 0.0),
 (627, 0.05),
 (628, 0.0),
 (629, 0.09284766908852593),
 (630, 0.0),
 (631, 0.0),
 (632, 0.0),
 (633, 0.0),
 (634, 0.0),
 (635, 0.0625),
 (636, 0.0),
 (637, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.06063390625908324),
 (641, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.019462473604038074),
 (645, 0.0),
 (646, 0.0),
 (647, 0.1563858105428061),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.0),
 (654, 0.04902903378454601),
 (655, 0.15000000000000002),
 (656, 0.0),
 (657, 0.0),
 (658, 0.0),
 (659, 0.0),
 (660, 0.0),
 (661, 0.0),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0),
 (665, 0.03857583749052298),
 (666, 0.0),
 (667, 0.0),
 (668, 0.0),
 (669, 0.0),
 (670, 0.11470786693528087),
 (671, 0.0),
 (672, 0.0),
 (673, 0.0),
 (674, 0.0),
 (675, 0.05212860351426869),
 (676, 0.0),
 (677, 0.0),
 (678, 0.04109974682633932),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),
 (682, 0.0472455591261534),
 (683, 0.0),
 (684, 0.0),
 (685, 0.08980265101338746),
 (686, 0.04003203845127178),
 (687, 0.05212860351426869),
 (688, 0.0314970394174356),
 (689, 0.0),
 (690, 0.037267799624996496),
 (691, 0.10425720702853739),
 (692, 0.0),
 (693, 0.0),
 (694, 0.0),
 (695, 0.0),
 (696, 0.1796053020267749),
 (697, 0.0),
 (698, 0.0),
 (699, 0.0),
 (700, 0.0),
 (701, 0.0),
 (702, 0.14173667737846019),
 (703, 0.0),
 (704, 0.03952847075210474),
 (705, 0.0),
 (706, 0.0),
 (707, 0.0),
 (708, 0.0),
 (709, 0.0),
 (710, 0.0),
 (711, 0.0),
 (712, 0.06454972243679027),
 (713, 0.0),
 (714, 0.0),
 (715, 0.0),
 (716, 0.0),
 (717, 0.0),
 (718, 0.0),
 (719, 0.0),
 (720, 0.0),
 (721, 0.041666666666666664),
 (722, 0.0),
 (723, 0.0),
 (724, 0.0),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (728, 0.0),
 (729, 0.053300179088902604),
 (730, 0.0545544725589981),
 (731, 0.0),
 (732, 0.0),
 (733, 0.06063390625908324),
 (734, 0.0),
 (735, 0.0545544725589981),
 (736, 0.0),
 (737, 0.0),
 (738, 0.0),
 (739, 0.15075567228888181),
 (740, 0.05423261445466404),
 (741, 0.037267799624996496),
 (742, 0.0),
 (743, 0.0),
 (744, 0.0),
 (745, 0.036860489038724284),
 (746, 0.0),
 (747, 0.0),
 (748, 0.0),
 (749, 0.0),
 (750, 0.0),
 (751, 0.041666666666666664),
 (752, 0.0),
 (753, 0.0),
 (754, 0.03125),
 (755, 0.0),
 (756, 0.0),
 (757, 0.0),
 (758, 0.0),
 (759, 0.0),
 (760, 0.0),
 (761, 0.0),
 (762, 0.0),
 (763, 0.0),
 (764, 0.04109974682633932),
 (765, 0.03500700210070024),
 (766, 0.0),
 (767, 0.0),
 (768, 0.0),
 (769, 0.0),
 (770, 0.0),
 (771, 0.0),
 (772, 0.0668153104781061),
 (773, 0.0),
 (774, 0.048112522432468816),
 (775, 0.03434014098717226),
 (776, 0.0),
 (777, 0.0),
 (778, 0.0),
 (779, 0.0),
 (780, 0.0),
 (781, 0.0),
 (782, 0.08838834764831843),
 (783, 0.0),
 (784, 0.07216878364870323),
 (785, 0.0),
 (786, 0.0),
 (787, 0.0),
 (788, 0.0),
 (789, 0.0),
 (790, 0.044194173824159216),
 (791, 0.0),
 (792, 0.05590169943749474),
 (793, 0.0),
 (794, 0.0),
 (795, 0.07216878364870323),
 (796, 0.0),
 (797, 0.05892556509887897),
 (798, 0.0),
 (799, 0.0),
 (800, 0.1336306209562122),
 (801, 0.13693063937629152),
 (802, 0.0),
 (803, 0.0),
 (804, 0.0),
 (805, 0.0),
 (806, 0.0),
 (807, 0.0),
 (808, 0.0),
 (809, 0.0),
 (810, 0.0),
 (811, 0.0),
 (812, 0.0),
 (813, 0.10939874362342092),
 (814, 0.06933752452815364),
 (815, 0.0),
 (816, 0.09682458365518541),
 (817, 0.0),
 (818, 0.0),
 (819, 0.0),
 (820, 0.05212860351426869),
 (821, 0.0),
 (822, 0.032009219983223994),
 (823, 0.05892556509887897),
 (824, 0.0),
 (825, 0.14433756729740643),
 (826, 0.0),
 (827, 0.0),
 (828, 0.0),
 (829, 0.0),
 (830, 0.07808688094430304),
 (831, 0.0),
 (832, 0.0),
 (833, 0.0),
 (834, 0.0),
 (835, 0.0),
 (836, 0.0),
 (837, 0.04003203845127178),
 (838, 0.0),
 (839, 0.046423834544262965),
 (840, 0.034020690871988585),
 (841, 0.0),
 (842, 0.0),
 (843, 0.0),
 (844, 0.0),
 (845, 0.0),
 (846, 0.033113308926626096),
 (847, 0.0),
 (848, 0.0),
 (849, 0.0),
 (850, 0.044194173824159216),
 (851, 0.051031036307982884),
 (852, 0.0),
 (853, 0.0),
 (854, 0.03125),
 (855, 0.0),
 (856, 0.0),
 (857, 0.0),
 (858, 0.0),
 (859, 0.0),
 (860, 0.0),
 (861, 0.0),
 (862, 0.050251890762960605),
 (863, 0.14744195615489714),
 (864, 0.0),
 (865, 0.0),
 (866, 0.0),
 (867, 0.0),
 (868, 0.036084391824351615),
 (869, 0.0),
 (870, 0.0),
 (871, 0.0),
 (872, 0.0206901472150592),
 (873, 0.05590169943749474),
 (874, 0.0),
 (875, 0.04564354645876384),
 (876, 0.0),
 (877, 0.0),
 (878, 0.0),
 (879, 0.04564354645876384),
 (880, 0.0),
 (881, 0.0),
 (882, 0.07372097807744857),
 (883, 0.06509445549041194),
 (884, 0.0),
 (885, 0.038124642583151166),
 (886, 0.0),
 (887, 0.0),
 (888, 0.0),
 (889, 0.0),
 (890, 0.0),
 (891, 0.0),
 (892, 0.0),
 (893, 0.0),
 (894, 0.0),
 (895, 0.0),
 (896, 0.0),
 (897, 0.0),
 (898, 0.0),
 (899, 0.06063390625908324),
 (900, 0.0),
 (901, 0.0),
 (902, 0.0),
 (903, 0.030542361089076306),
 (904, 0.05212860351426869),
 (905, 0.0),
 (906, 0.0),
 (907, 0.0),
 (908, 0.033113308926626096),
 (909, 0.0),
 (910, 0.0),
 (911, 0.0),
 (912, 0.0),
 (913, 0.0),
 (914, 0.0),
 (915, 0.05590169943749474),
 (916, 0.0),
 (917, 0.0),
 (918, 0.0),
 (919, 0.0),
 (920, 0.0),
 (921, 0.0),
 (922, 0.0),
 (923, 0.0),
 (924, 0.0545544725589981),
 (925, 0.0),
 (926, 0.05),
 (927, 0.08006407690254357),
 (928, 0.0),
 (929, 0.0),
 (930, 0.0),
 (931, 0.0),
 (932, 0.0),
 (933, 0.0),
 (934, 0.09622504486493763),
 (935, 0.10206207261596577),
 (936, 0.040555355282690636),
 (937, 0.0),
 (938, 0.0),
 (939, 0.0472455591261534),
 (940, 0.04109974682633932),
 (941, 0.09128709291752768),
 (942, 0.0),
 (943, 0.0),
 (944, 0.0),
 (945, 0.04490132550669373),
 (946, 0.0545544725589981),
 (947, 0.0),
 (948, 0.0),
 (949, 0.036860489038724284),
 (950, 0.0),
 (951, 0.0),
 (952, 0.0),
 (953, 0.0),
 (954, 0.0),
 (955, 0.0),
 (956, 0.0),
 (957, 0.15309310892394865),
 (958, 0.0),
 (959, 0.0),
 (960, 0.0),
 (961, 0.0),
 (962, 0.20801257358446093),
 (963, 0.0),
 (964, 0.0),
 (965, 0.0),
 (966, 0.15309310892394865),
 (967, 0.0),
 (968, 0.04351941398892446),
 (969, 1.0),
 (970, 0.0),
 (971, 0.03857583749052298),
 (972, 0.0),
 (973, 0.0472455591261534),
 (974, 0.0625),
 (975, 0.0),
 (976, 0.0),
 (977, 0.0),
 (978, 0.07808688094430304),
 (979, 0.1336306209562122),
 (980, 0.0),
 (981, 0.0),
 (982, 0.0),
 (983, 0.06063390625908324),
 (984, 0.0),
 (985, 0.0),
 (986, 0.040555355282690636),
 (987, 0.057353933467640436),
 (988, 0.042257712736425826),
 (989, 0.0),
 (990, 0.0),
 (991, 0.0),
 (992, 0.0),
 (993, 0.0),
 (994, 0.044194173824159216),
 (995, 0.0),
 (996, 0.0),
 (997, 0.0),
 (998, 0.08574929257125441),
 (999, 0.0),
 ...]

In [27]:
# finding length
len(similarity_score)

10000

In [28]:
# sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score, reverse=True, key = lambda vector:vector[1])
sorted_similar_movies

[(969, 1.0),
 (3993, 0.3244428422615251),
 (3563, 0.32274861218395134),
 (9171, 0.32274861218395134),
 (4424, 0.2773500981126146),
 (1813, 0.2668724980820582),
 (6089, 0.2551551815399144),
 (1727, 0.25),
 (4749, 0.25),
 (8026, 0.25),
 (5772, 0.24253562503633297),
 (6216, 0.24253562503633297),
 (7020, 0.24253562503633297),
 (6570, 0.2405626121623441),
 (2100, 0.2401922307076307),
 (7146, 0.24019223070763068),
 (8885, 0.23570226039551587),
 (9470, 0.23570226039551587),
 (3185, 0.22941573387056174),
 (6477, 0.2282177322938192),
 (5538, 0.22613350843332275),
 (9729, 0.22613350843332272),
 (2929, 0.22360679774997896),
 (8680, 0.22360679774997896),
 (1987, 0.2182178902359924),
 (5092, 0.2182178902359924),
 (6288, 0.2175970699446223),
 (561, 0.2165063509461097),
 (6837, 0.21320071635561041),
 (9360, 0.21128856368212912),
 (7101, 0.20851441405707477),
 (9325, 0.20851441405707477),
 (962, 0.20801257358446093),
 (1405, 0.20801257358446093),
 (4890, 0.20801257358446093),
 (5891, 0.20801257358446093),
 (6836, 0.20801257358446093),
 (8113, 0.20801257358446093),
 (9419, 0.20801257358446093),
 (5278, 0.20412414523193154),
 (2276, 0.2004459314343183),
 (2846, 0.2004459314343183),
 (8914, 0.2004459314343183),
 (9861, 0.2004459314343183),
 (2417, 0.2),
 (2730, 0.19364916731037082),
 (3366, 0.19364916731037082),
 (3540, 0.19364916731037082),
 (7368, 0.19364916731037082),
 (7914, 0.19364916731037082),
 (9103, 0.19364916731037082),
 (9996, 0.19364916731037082),
 (9088, 0.1889822365046136),
 (5926, 0.1875),
 (6155, 0.1875),
 (6392, 0.1875),
 (6825, 0.1875),
 (7962, 0.1875),
 (8104, 0.1875),
 (8912, 0.1875),
 (9267, 0.1875),
 (9905, 0.1875),
 (9931, 0.1875),
 (35, 0.18569533817705186),
 (342, 0.18569533817705186),
 (4511, 0.18569533817705186),
 (5314, 0.18569533817705186),
 (5412, 0.18569533817705186),
 (2391, 0.18257418583505536),
 (3327, 0.18190171877724973),
 (3447, 0.18190171877724973),
 (3794, 0.18190171877724973),
 (3917, 0.18190171877724973),
 (5040, 0.18190171877724973),
 (5682, 0.18190171877724973),
 (7295, 0.18190171877724973),
 (7768, 0.18190171877724973),
 (8158, 0.18190171877724973),
 (9638, 0.18190171877724973),
 (9910, 0.18190171877724973),
 (9002, 0.18042195912175807),
 (696, 0.1796053020267749),
 (1738, 0.1796053020267749),
 (1722, 0.1767766952966369),
 (1947, 0.1767766952966369),
 (2111, 0.1767766952966369),
 (2968, 0.1767766952966369),
 (3396, 0.1767766952966369),
 (3587, 0.1767766952966369),
 (4577, 0.1767766952966369),
 (4783, 0.1767766952966369),
 (5423, 0.1767766952966369),
 (6306, 0.1767766952966369),
 (7222, 0.1767766952966369),
 (8436, 0.1767766952966369),
 (9101, 0.1767766952966369),
 (9474, 0.1767766952966369),
 (9615, 0.1767766952966369),
 (9893, 0.1767766952966369),
 (8029, 0.17677669529663687),
 (9274, 0.17677669529663687),
 (258, 0.17407765595569785),
 (8344, 0.17407765595569785),
 (1289, 0.1720618004029213),
 (2348, 0.1720618004029213),
 (4655, 0.1720618004029213),
 (6900, 0.1720618004029213),
 (7412, 0.1720618004029213),
 (8524, 0.1720618004029213),
 (9529, 0.1720618004029213),
 (7521, 0.1717007049358613),
 (1742, 0.16854996561581054),
 (443, 0.16770509831248423),
 (1253, 0.16770509831248423),
 (2740, 0.16770509831248423),
 (3770, 0.16770509831248423),
 (3915, 0.16770509831248423),
 (3946, 0.16770509831248423),
 (5476, 0.16770509831248423),
 (5586, 0.16770509831248423),
 (5735, 0.16770509831248423),
 (5823, 0.16770509831248423),
 (6468, 0.16770509831248423),
 (7179, 0.16770509831248423),
 (7490, 0.16770509831248423),
 (7818, 0.16770509831248423),
 (7935, 0.16770509831248423),
 (7969, 0.16770509831248423),
 (8220, 0.16770509831248423),
 (9757, 0.16770509831248423),
 (3237, 0.16703827619526523),
 (7290, 0.16703827619526523),
 (134, 0.16666666666666666),
 (410, 0.16666666666666666),
 (6014, 0.16666666666666666),
 (7567, 0.16666666666666666),
 (8794, 0.16666666666666666),
 (3462, 0.1643989873053573),
 (4391, 0.1643989873053573),
 (9261, 0.1643989873053573),
 (1990, 0.1636634176769943),
 (2268, 0.1636634176769943),
 (2370, 0.1636634176769943),
 (3201, 0.1636634176769943),
 (3572, 0.1636634176769943),
 (4356, 0.1636634176769943),
 (4551, 0.1636634176769943),
 (5140, 0.1636634176769943),
 (5169, 0.1636634176769943),
 (7177, 0.1636634176769943),
 (7273, 0.1636634176769943),
 (7280, 0.1636634176769943),
 (7569, 0.1636634176769943),
 (1919, 0.16222142113076254),
 (4412, 0.16012815380508713),
 (8535, 0.16012815380508713),
 (8725, 0.15990053726670783),
 (54, 0.1599005372667078),
 (433, 0.1599005372667078),
 (568, 0.1599005372667078),
 (2345, 0.1599005372667078),
 (2935, 0.1599005372667078),
 (3347, 0.1599005372667078),
 (3931, 0.1599005372667078),
 (4421, 0.1599005372667078),
 (4456, 0.1599005372667078),
 (4641, 0.1599005372667078),
 (4984, 0.1599005372667078),
 (5082, 0.1599005372667078),
 (5360, 0.1599005372667078),
 (5546, 0.1599005372667078),
 (5997, 0.1599005372667078),
 (7825, 0.1599005372667078),
 (8085, 0.1599005372667078),
 (8793, 0.1599005372667078),
 (8816, 0.1599005372667078),
 (9680, 0.1599005372667078),
 (4937, 0.15811388300841897),
 (5627, 0.15811388300841897),
 (6196, 0.15811388300841897),
 (8140, 0.15811388300841897),
 (8654, 0.15811388300841897),
 (647, 0.1563858105428061),
 (2971, 0.1563858105428061),
 (3175, 0.1563858105428061),
 (3380, 0.1563858105428061),
 (4529, 0.1563858105428061),
 (6126, 0.1563858105428061),
 (7482, 0.1563858105428061),
 (8251, 0.1563858105428061),
 (9044, 0.1563858105428061),
 (374, 0.15625),
 (2534, 0.15617376188860607),
 (7759, 0.15617376188860607),
 (9505, 0.15617376188860607),
 (7251, 0.1543033499620919),
 (957, 0.15309310892394865),
 (966, 0.15309310892394865),
 (1246, 0.15309310892394865),
 (1424, 0.15309310892394865),
 (2438, 0.15309310892394865),
 (2679, 0.15309310892394865),
 (2778, 0.15309310892394865),
 (3250, 0.15309310892394865),
 (3932, 0.15309310892394865),
 (4263, 0.15309310892394865),
 (4639, 0.15309310892394865),
 (5449, 0.15309310892394865),
 (5885, 0.15309310892394865),
 (6772, 0.15309310892394865),
 (9854, 0.15309310892394865),
 (9998, 0.15309310892394865),
 (8511, 0.15249857033260467),
 (8983, 0.15249857033260467),
 (739, 0.15075567228888181),
 (2376, 0.15075567228888181),
 (2412, 0.15075567228888181),
 (4171, 0.15075567228888181),
 (6727, 0.15075567228888181),
 (8345, 0.15075567228888181),
 (8414, 0.15075567228888181),
 (9109, 0.15075567228888181),
 (9304, 0.15075567228888181),
 (9581, 0.15075567228888181),
 (9917, 0.15075567228888181),
 (9982, 0.15075567228888181),
 (655, 0.15000000000000002),
 (2077, 0.15000000000000002),
 (3197, 0.15000000000000002),
 (3767, 0.15000000000000002),
 (4887, 0.15000000000000002),
 (5936, 0.15000000000000002),
 (6042, 0.15000000000000002),
 (6879, 0.15000000000000002),
 (8882, 0.15000000000000002),
 (9090, 0.15000000000000002),
 (9971, 0.15000000000000002),
 (510, 0.14744195615489714),
 (863, 0.14744195615489714),
 (6006, 0.14744195615489714),
 (1647, 0.14708710135363803),
 (4167, 0.14708710135363803),
 (4722, 0.14708710135363803),
 (5124, 0.14708710135363803),
 (5792, 0.14708710135363803),
 (6993, 0.14708710135363803),
 (7642, 0.14708710135363803),
 (7643, 0.14708710135363803),
 (8255, 0.14708710135363803),
 (9003, 0.14708710135363803),
 (9072, 0.14708710135363803),
 (9140, 0.14708710135363803),
 (1962, 0.14586499149789456),
 (1999, 0.14586499149789456),
 (8656, 0.14586499149789456),
 (9165, 0.14586499149789456),
 (9967, 0.14586499149789456),
 (1258, 0.14433756729740646),
 (2802, 0.14433756729740646),
 (3060, 0.14433756729740646),
 (3430, 0.14433756729740646),
 (7553, 0.14433756729740646),
 (8529, 0.14433756729740646),
 (8602, 0.14433756729740646),
 (9390, 0.14433756729740646),
 (825, 0.14433756729740643),
 (2258, 0.14433756729740643),
 (5250, 0.14433756729740643),
 (6776, 0.14433756729740643),
 (9866, 0.14433756729740643),
 (702, 0.14173667737846019),
 (1139, 0.14173667737846019),
 (1151, 0.14173667737846019),
 (1938, 0.14173667737846019),
 (2237, 0.14173667737846019),
 (2850, 0.14173667737846019),
 (5783, 0.14173667737846019),
 (6739, 0.14173667737846019),
 (7758, 0.14173667737846019),
 (8284, 0.14173667737846019),
 (8425, 0.14173667737846019),
 (501, 0.1414213562373095),
 (9749, 0.14002800840280097),
 (3111, 0.1392715036327889),
 (3997, 0.1392715036327889),
 (4375, 0.1392715036327889),
 (7349, 0.1392715036327889),
 (7976, 0.1392715036327889),
 (8298, 0.1392715036327889),
 (8394, 0.1392715036327889),
 (8941, 0.1392715036327889),
 (9057, 0.1392715036327889),
 (2741, 0.1386750490563073),
 (3765, 0.1386750490563073),
 (5963, 0.1386750490563073),
 (6156, 0.1386750490563073),
 (6182, 0.1386750490563073),
 (6323, 0.1386750490563073),
 (6711, 0.1386750490563073),
 (7591, 0.1386750490563073),
 (8304, 0.1386750490563073),
 (8585, 0.1386750490563073),
 (8643, 0.1386750490563073),
 (1896, 0.13736056394868904),
 (801, 0.13693063937629152),
 (1346, 0.13693063937629152),
 (2564, 0.13693063937629152),
 (3228, 0.13693063937629152),
 (3726, 0.13693063937629152),
 (6130, 0.13693063937629152),
 (6535, 0.13693063937629152),
 (7004, 0.13693063937629152),
 (7557, 0.13693063937629152),
 (8466, 0.13608276348795434),
 (2078, 0.13470397652008118),
 (2859, 0.13470397652008118),
 (3381, 0.13470397652008118),
 (3846, 0.13470397652008118),
 (4274, 0.13470397652008118),
 (5403, 0.13470397652008118),
 (6778, 0.13470397652008118),
 (7560, 0.13470397652008118),
 (535, 0.1336306209562122),
 (800, 0.1336306209562122),
 (979, 0.1336306209562122),
 (1178, 0.1336306209562122),
 (1344, 0.1336306209562122),
 (1797, 0.1336306209562122),
 (2434, 0.1336306209562122),
 (3596, 0.1336306209562122),
 (3728, 0.1336306209562122),
 (4829, 0.1336306209562122),
 (5599, 0.1336306209562122),
 (5615, 0.1336306209562122),
 (6313, 0.1336306209562122),
 (6350, 0.1336306209562122),
 (6831, 0.1336306209562122),
 (7344, 0.1336306209562122),
 (8076, 0.1336306209562122),
 (8259, 0.1336306209562122),
 (8395, 0.1336306209562122),
 (8844, 0.1336306209562122),
 (9518, 0.1336306209562122),
 (500, 0.13258252147247765),
 (1558, 0.13258252147247765),
 (3216, 0.13258252147247765),
 (5924, 0.13258252147247765),
 (6895, 0.13258252147247765),
 (6906, 0.13258252147247765),
 (7451, 0.13258252147247765),
 (7537, 0.13258252147247765),
 (7705, 0.13258252147247765),
 (7714, 0.13258252147247765),
 (9098, 0.13258252147247765),
 (9710, 0.13258252147247765),
 (5812, 0.13245323570650439),
 (2274, 0.13130643285972254),
 (1185, 0.1305582419667734),
 (2504, 0.1305582419667734),
 (2949, 0.1305582419667734),
 (3827, 0.1305582419667734),
 (5322, 0.1305582419667734),
 (6420, 0.1305582419667734),
 (8543, 0.1305582419667734),
 (8897, 0.1305582419667734),
 (9050, 0.1305582419667734),
 (9506, 0.1305582419667734),
 (99, 0.12909944487358055),
 (1109, 0.12909944487358055),
 (3212, 0.12909944487358055),
 (3701, 0.12909944487358055),
 (3886, 0.12909944487358055),
 (4254, 0.12909944487358055),
 (4262, 0.12909944487358055),
 (4831, 0.12909944487358055),
 (4842, 0.12909944487358055),
 (5768, 0.12909944487358055),
 (5779, 0.12909944487358055),
 (5983, 0.12909944487358055),
 (6345, 0.12909944487358055),
 (6356, 0.12909944487358055),
 (6613, 0.12909944487358055),
 (8279, 0.12909944487358055),
 (8514, 0.12909944487358055),
 (8751, 0.12909944487358055),
 (9156, 0.12909944487358055),
 (9903, 0.12909944487358055),
 (9926, 0.12909944487358055),
 (9986, 0.12909944487358055),
 (2292, 0.12862393885688161),
 (3894, 0.12862393885688161),
 (5049, 0.12862393885688161),
 (5603, 0.12862393885688161),
 (6865, 0.12862393885688161),
 (8303, 0.12862393885688161),
 (6152, 0.12803687993289598),
 (5307, 0.1270001270001905),
 (8386, 0.1270001270001905),
 (2098, 0.1267731382092775),
 (7852, 0.1267731382092775),
 (8766, 0.1267731382092775),
 (1398, 0.125),
 (1565, 0.125),
 (1978, 0.125),
 (1996, 0.125),
 (2179, 0.125),
 (2377, 0.125),
 (2494, 0.125),
 (2616, 0.125),
 (2625, 0.125),
 (2687, 0.125),
 (2926, 0.125),
 (3437, 0.125),
 (3578, 0.125),
 (3887, 0.125),
 (4260, 0.125),
 (4458, 0.125),
 (4817, 0.125),
 (5942, 0.125),
 (5945, 0.125),
 (6314, 0.125),
 (6691, 0.125),
 (6725, 0.125),
 (6953, 0.125),
 (7421, 0.125),
 (7427, 0.125),
 (7486, 0.125),
 (7658, 0.125),
 (7833, 0.125),
 (7869, 0.125),
 (8409, 0.125),
 (8417, 0.125),
 (8573, 0.125),
 (8772, 0.125),
 (9246, 0.125),
 (9272, 0.125),
 (9489, 0.125),
 (9742, 0.125),
 (223, 0.12329924047901797),
 (225, 0.12329924047901797),
 (502, 0.12329924047901797),
 (2817, 0.12329924047901797),
 (4080, 0.12329924047901797),
 (4172, 0.12329924047901797),
 (4478, 0.12329924047901797),
 (4615, 0.12329924047901797),
 (6433, 0.12329924047901797),
 (6989, 0.12329924047901797),
 (7249, 0.12329924047901797),
 (8163, 0.12329924047901797),
 (9337, 0.12329924047901797),
 (1045, 0.12166606584807191),
 (2467, 0.12166606584807191),
 (4268, 0.12166606584807191),
 (4803, 0.12166606584807191),
 (6090, 0.12166606584807191),
 (7365, 0.12166606584807191),
 (7891, 0.12166606584807191),
 (8232, 0.12166606584807191),
 (8639, 0.12166606584807191),
 (9547, 0.12166606584807191),
 (253, 0.12126781251816648),
 (467, 0.12126781251816648),
 (520, 0.12126781251816648),
 (1274, 0.12126781251816648),
 (2705, 0.12126781251816648),
 (3320, 0.12126781251816648),
 (3346, 0.12126781251816648),
 (3959, 0.12126781251816648),
 (4041, 0.12126781251816648),
 (4124, 0.12126781251816648),
 (4912, 0.12126781251816648),
 (5026, 0.12126781251816648),
 (5400, 0.12126781251816648),
 (5821, 0.12126781251816648),
 (5892, 0.12126781251816648),
 (6003, 0.12126781251816648),
 (6013, 0.12126781251816648),
 (6286, 0.12126781251816648),
 (6459, 0.12126781251816648),
 (6824, 0.12126781251816648),
 (7093, 0.12126781251816648),
 (7095, 0.12126781251816648),
 (7253, 0.12126781251816648),
 (7493, 0.12126781251816648),
 (7531, 0.12126781251816648),
 (7761, 0.12126781251816648),
 (8111, 0.12126781251816648),
 (8252, 0.12126781251816648),
 (8287, 0.12126781251816648),
 (8506, 0.12126781251816648),
 (8629, 0.12126781251816648),
 (8920, 0.12126781251816648),
 (9013, 0.12126781251816648),
 (9200, 0.12126781251816648),
 (9323, 0.12126781251816648),
 (9755, 0.12126781251816648),
 (9901, 0.12126781251816648),
 (8959, 0.1203858530857692),
 (2042, 0.12009611535381534),
 (3750, 0.12009611535381534),
 (4661, 0.12009611535381534),
 (5570, 0.12009611535381534),
 (6932, 0.12009611535381534),
 (7840, 0.12009611535381534),
 (8584, 0.12009611535381534),
 (8673, 0.12009611535381534),
 (8803, 0.12009611535381534),
 (7887, 0.11952286093343936),
 (1457, 0.11858541225631422),
 (4044, 0.11858541225631422),
 (5375, 0.11858541225631422),
 (5639, 0.11858541225631422),
 (7806, 0.11858541225631422),
 (8310, 0.11858541225631422),
 (189, 0.11785113019775793),
 (1304, 0.11785113019775793),
 (1668, 0.11785113019775793),
 (1768, 0.11785113019775793),
 (4475, 0.11785113019775793),
 (4860, 0.11785113019775793),
 (4920, 0.11785113019775793),
 (5158, 0.11785113019775793),
 (5604, 0.11785113019775793),
 (5939, 0.11785113019775793),
 (5966, 0.11785113019775793),
 (6189, 0.11785113019775793),
 (6713, 0.11785113019775793),
 (7292, 0.11785113019775793),
 (7304, 0.11785113019775793),
 (7430, 0.11785113019775793),
 (7586, 0.11785113019775793),
 (7699, 0.11785113019775793),
 (8780, 0.11785113019775793),
 (9104, 0.11785113019775793),
 (9208, 0.11785113019775793),
 (9209, 0.11785113019775793),
 (9335, 0.11785113019775793),
 (9405, 0.11785113019775793),
 (9551, 0.11785113019775793),
 (9577, 0.11785113019775793),
 (9801, 0.11785113019775793),
 (1318, 0.11713032141645455),
 (1840, 0.11713032141645455),
 (2016, 0.11713032141645455),
 (7511, 0.11713032141645455),
 (8373, 0.11713032141645455),
 (9819, 0.11713032141645455),
 (34, 0.11572751247156893),
 (42, 0.11572751247156893),
 (3385, 0.11572751247156893),
 (6600, 0.11572751247156893),
 (9542, 0.11572751247156893),
 (9788, 0.11572751247156893),
 (670, 0.11470786693528087),
 (1529, 0.11470786693528087),
 (1583, 0.11470786693528087),
 (1711, 0.11470786693528087),
 (1864, 0.11470786693528087),
 (1953, 0.11470786693528087),
 (2527, 0.11470786693528087),
 (3085, 0.11470786693528087),
 (3394, 0.11470786693528087),
 (3552, 0.11470786693528087),
 (3638, 0.11470786693528087),
 (3954, 0.11470786693528087),
 (4128, 0.11470786693528087),
 (4141, 0.11470786693528087),
 (4176, 0.11470786693528087),
 (4232, 0.11470786693528087),
 (4419, 0.11470786693528087),
 (4904, 0.11470786693528087),
 (5479, 0.11470786693528087),
 (5767, 0.11470786693528087),
 (6522, 0.11470786693528087),
 (6557, 0.11470786693528087),
 (6633, 0.11470786693528087),
 (7336, 0.11470786693528087),
 (7410, 0.11470786693528087),
 (8378, 0.11470786693528087),
 (8403, 0.11470786693528087),
 (8719, 0.11470786693528087),
 (8776, 0.11470786693528087),
 (9545, 0.11470786693528087),
 (2205, 0.1143739277494535),
 (5063, 0.1143739277494535),
 (5483, 0.1143739277494535),
 (6561, 0.1143739277494535),
 (6670, 0.1143739277494535),
 (1545, 0.11306675421666136),
 (3378, 0.11306675421666136),
 (5039, 0.11306675421666136),
 (7023, 0.11306675421666136),
 (7393, 0.11306675421666136),
 (8160, 0.11306675421666136),
 (1175, 0.1118033988749895),
 (1236, 0.1118033988749895),
 (1249, 0.1118033988749895),
 (5824, 0.1118033988749895),
 (8792, 0.1118033988749895),
 (104, 0.11180339887498948),
 (206, 0.11180339887498948),
 (376, 0.11180339887498948),
 (1066, 0.11180339887498948),
 (1305, 0.11180339887498948),
 (1487, 0.11180339887498948),
 (1907, 0.11180339887498948),
 (1939, 0.11180339887498948),
 (2136, 0.11180339887498948),
 (2644, 0.11180339887498948),
 (3601, 0.11180339887498948),
 (3859, 0.11180339887498948),
 (3943, 0.11180339887498948),
 (4247, 0.11180339887498948),
 (4491, 0.11180339887498948),
 (4769, 0.11180339887498948),
 (4877, 0.11180339887498948),
 (5296, 0.11180339887498948),
 (5397, 0.11180339887498948),
 (5453, 0.11180339887498948),
 (5728, 0.11180339887498948),
 (6465, 0.11180339887498948),
 (6816, 0.11180339887498948),
 (7631, 0.11180339887498948),
 (7998, 0.11180339887498948),
 (8595, 0.11180339887498948),
 (8660, 0.11180339887498948),
 (8972, 0.11180339887498948),
 (9191, 0.11180339887498948),
 (9438, 0.11180339887498948),
 (9658, 0.11180339887498948),
 (9948, 0.11180339887498948),
 (338, 0.11058146711617285),
 (2187, 0.11058146711617285),
 (5267, 0.11058146711617285),
 (6720, 0.11058146711617285),
 (8499, 0.11043152607484653),
 (6276, 0.10976425998969035),
 (813, 0.10939874362342092),
 (2407, 0.10939874362342092),
 (6573, 0.10939874362342092),
 (9997, 0.10939874362342092),
 (228, 0.1091089451179962),
 (315, 0.1091089451179962),
 (445, 0.1091089451179962),
 (1208, 0.1091089451179962),
 (1453, 0.1091089451179962),
 (1622, 0.1091089451179962),
 (1625, 0.1091089451179962),
 (2333, 0.1091089451179962),
 (3478, 0.1091089451179962),
 (3808, 0.1091089451179962),
 (3828, 0.1091089451179962),
 (3862, 0.1091089451179962),
 (4488, 0.1091089451179962),
 (4614, 0.1091089451179962),
 (5165, 0.1091089451179962),
 (5213, 0.1091089451179962),
 (5531, 0.1091089451179962),
 (5623, 0.1091089451179962),
 (5886, 0.1091089451179962),
 (6431, 0.1091089451179962),
 (6590, 0.1091089451179962),
 (7069, 0.1091089451179962),
 (7142, 0.1091089451179962),
 (7274, 0.1091089451179962),
 (7520, 0.1091089451179962),
 (7723, 0.1091089451179962),
 (7775, 0.1091089451179962),
 (8074, 0.1091089451179962),
 (8227, 0.1091089451179962),
 (8597, 0.1091089451179962),
 (8901, 0.1091089451179962),
 (9288, 0.1091089451179962),
 (9832, 0.1091089451179962),
 (6001, 0.10825317547305485),
 (6736, 0.10825317547305485),
 (7800, 0.10825317547305485),
 (9566, 0.10825317547305485),
 (2071, 0.10714285714285714),
 (3232, 0.10714285714285714),
 (3329, 0.10714285714285714),
 (4972, 0.10714285714285714),
 (7697, 0.10714285714285714),
 (9774, 0.10714285714285714),
 (252, 0.10660035817780521),
 (1019, 0.10660035817780521),
 (1390, 0.10660035817780521),
 (2777, 0.10660035817780521),
 (3115, 0.10660035817780521),
 (3326, 0.10660035817780521),
 (3481, 0.10660035817780521),
 (4063, 0.10660035817780521),
 (4636, 0.10660035817780521),
 (4975, 0.10660035817780521),
 (5011, 0.10660035817780521),
 (5357, 0.10660035817780521),
 (5380, 0.10660035817780521),
 (5444, 0.10660035817780521),

In [29]:
# print the name of similar movies based on the index
print("Movies suggested for you:\n")
for i in sorted_similar_movies[:10]:
    print(movies.iloc[i[0]].title)

Movies suggested for you:

Iron Man
Iron Man 2
Iron Man 3
The Lawnmower Man
Mazinger Z: Infinity
Spider-Man: Homecoming
Outlander
Justice League Dark
Ransom
The 6th Day

In [30]:
# Movies Recommandation System

movie_name =input("Enter your favourite movie name: ")

list_of_all_titles=movies["title"].tolist()

related_movie=difflib.get_close_matches(movie_name,list_of_all_titles)

matched = related_movie[0]

index_of_movie = movies[movies.title==matched].index[0]

similarity_score = list(enumerate(similarity[index_of_movie]))

sorted_similar_movies = sorted(similarity_score, reverse=True, key = lambda vector:vector[1])

print("Movies suggested for you:\n")
for i in sorted_similar_movies[:10]:
    print(movies.iloc[i[0]].title)

Movies suggested for you:

Iron Man
Iron Man 2
Iron Man 3
The Lawnmower Man
Mazinger Z: Infinity
Spider-Man: Homecoming
Outlander
Justice League Dark
Ransom
The 6th Day